### ISSUE TITLE
Visualize mesh files

### ISSUE THREAD

**Issue by lee-orr** [brendanjmeade/celeri_ui#10]
Load and visualize meshes.  These are in the .msh format, and the primary goal is to visualize them.  We will not manipulate these data, but we may want to manipulate segments to follow some mesh edges.  See below.

**Comment by jploveless** [comment]
@lee-orr Could you provide some guidance about this new enhancement? I'm not seeing it in the current UI, and when looking at the commit, it seems there are some warnings indicating missing components (e.g. `Cannot find module 'Components/MeshPanel' or its corresponding type declarations.`) Thanks!

**Comment by lee-orr** [comment]
@jploveless - Sorry about that - I had left for a dog walk while it was building, and the build failed to publish. As a result, the enhancement didn't appear yet. You can see the status of the latest build here: https://github.com/brendanjmeade/celeri_ui/actions - that way you can find out if the feature has actually been published.

I will see if I can adjust the automated closing of tickets to be based on when a commit successfully builds, rather than when it is initially pushed, to help reduce this kind of confusion.

On a more specific

**Comment by brendanjmeade** [comment]
@lee-orr @jploveless It's deployed now and I can see the mesh option but I don't see a mesh being plotted.  I would expect it to be right in the center of the region shown in the attached screenshot.
<img width="1311" alt="Screen Shot 2022-03-09 at 1 57 04 PM" src="https://user-images.githubusercontent.com/4225359/157512217-bd74c5ca-985a-4862-8e5a-2abafe0c6bb5.png">

**Comment by lee-orr** [comment]
Is the `Mesh Files` dropdown empty? If so - that'll be the cause of the issue - you just need to select the mesh file there.
It seems I made a mistake in terms of figuring out the actual origin file for a mesh - I'll add the ability for it to automatically load in the morning. But for now - you should be able to view it by actively choosing the mesh.

**Comment by lee-orr** [comment]
![image](https://user-images.githubusercontent.com/10376144/157513699-6eb0d65b-6e32-435c-877a-92688585577d.png)

**Comment by lee-orr** [comment]
@jploveless @brendanjmeade - before I fully close this, do you want to plot any information regarding the z coordinate of the vertices? At the moment, those are fully ignored.

**Comment by jploveless** [comment]
@lee-orr Here is a screenshot of the Nankai mesh from the program that generated it, [Gmsh](https://gmsh.info). I think you're right that this mesh has some one-dimensional elements listed in its file (tracing the perimeter of the mesh) but we want to focus on visualization of the 2-D elements, which begin on line 2405 of `nankai.msh`.
<img width="1117" alt="Screen Shot 2022-03-15 at 12 31 18 PM" src="https://user-images.githubusercontent.com/7537266/158426753-fe4cc346-abaa-4f58-b621-b7653937d14a.png">

**Comment by jploveless** [comment]
For reference, here are screenshots of `japan.msh`:

<img width="677" alt="Screen Shot 2022-03-15 at 12 36 18 PM" src="https://user-images.githubusercontent.com/7537266/158427185-bb8d298a-5c3f-4773-abff-4433e2088e55.png">

and `sagami.msh`:

<img width="1039" alt="Screen Shot 2022-03-15 at 12 35 36 PM" src="https://user-images.githubusercontent.com/7537266/158427220-1fbb8f85-26c9-4dab-a412-29ee8d46d604.png">

**Comment by lee-orr** [comment]
@jploveless - Thanks. Do the color changes have significance?

**Comment by lee-orr** [comment]
The meshes should now be showing up correctly, but still only one at a time

**Comment by brendanjmeade** [comment]
The Nankai mesh looks really good!  Can you automate the plotting of all meshes referenced in a mesh_parameters.json file?

**Comment by lee-orr** [comment]
That is being published as I type this - should be up in 10 minutes or so

**Comment by brendanjmeade** [comment]
@lee-orr Looks fantastic!  Thanks for the figures @jploveless!
