### ISSUE TITLE
Add additional mapbox maps

### ISSUE THREAD

**Issue by lee-orr** [brendanjmeade/celeri_ui#13]

**Comment by lee-orr** [comment]
Add ability to replace the mapbox map with grayscale, political or potentially other maps

**Comment by brendanjmeade** [comment]
@lee-orr I found a few examples of the types of map layers that we'd like to have:

1. [Hillshading](https://docs.mapbox.com/mapbox-gl-js/example/hillshade/)
2. [Hillshading](https://docs.mapbox.com/studio-manual/examples/hillshade/)
3. [Political boundaries](https://blog.mapbox.com/dynamically-change-disputed-national-borders-14c820cae923)

**Comment by lee-orr** [comment]
@brendanjmeade, @jploveless & @Emilycm-97 - I've implemented this feature so that it includes a few default maps, but also has the ability to let you add custom maps as you wish. You can generate those maps using mapbox studio, or by finding a link. Here is an example where I'm using a custom blueprint-style map: 
![image](https://user-images.githubusercontent.com/10376144/162785738-bc651c45-37bd-42f1-997d-5bd3d8b38891.png)

**Comment by brendanjmeade** [comment]
@lee-orr Works great now.  Thanks!
