### ISSUE TITLE
Visualization of segment properties

### ISSUE THREAD

**Issue by brendanjmeade** [brendanjmeade/celeri_ui#17]
Visualization of segment properties.  A great way to see a lot of information at once would be to be able to see the specific segment properties for all segments plotted on at the segments centroids.  For example: plot the locking depth values centered at segment centroids.  Or plot the segment names at the segment centroids.  Or any of the other properties.  One at a time, of course.

**Comment by brendanjmeade** [comment]
@lee-orr The answer is b.  Text on the screen next to all fault segments!

**Comment by lee-orr** [comment]
Added visualization to both segments & generic segments (i.e. arbitrary CSV files)

**Comment by brendanjmeade** [comment]
I'm excited to look at this.  How do we activate it?  I haven't been able to find it in the UI.

**Comment by brendanjmeade** [comment]
It's working for me now!  The styling looks really good and having the text parallel to the fault segments is elegant.  Two things to modify

1. Test (e.g., names/longitudes) only show up for a few segments at time.  This certainly help with readability.  Can we make is so that the text shows up for all segments?  This is much less readable but it helps us to look for things that are interesting/anamolous.
<img width="1076" alt="Screen Shot 2022-03-30 at 4 35 13 PM" src="https://user-images.githubusercontent.com/4225359/160926305-d5b7ad01-a4d5-44c3-92e3-18cb8c9b9b39.png">

2. Eliminate repeated text along the same segment.  In the figure below, the text a given fault segment appears three times.  We'd like it to only appear once near the middle of the fault segment.

<img width="837" alt="Screen Shot 2022-03-30 at 4 36 20 PM" src="https://user-images.githubusercontent.com/4225359/160926431-2c0900f2-3894-44ca-a987-b32242419211.png">

**Comment by lee-orr** [comment]
Adjusted things - I fully fixed (2), however showing all the labels at once leads to an unreadable mess: 
![image](https://user-images.githubusercontent.com/10376144/161548142-0349e5ae-a3ee-4e2d-9be6-725d0b9aeeae.png)
As such - I enabled collision detection on them, but removed the factor of line-length in the filtering, so all points show up unless there's a collision in the label - which leads to it looking like this:
![image](https://user-images.githubusercontent.com/10376144/161548320-bfdd929d-35a0-410d-ab15-ed504c7f79fb.png)
but still showing all the data when zoomed in:
![image](https://user-images.githubusercontent.com/10376144/161548371-cf90fb2d-d742-4d3a-918d-302335cca26f.png)

**Comment by brendanjmeade** [comment]
Simply fantastic!!!

**Comment by brendanjmeade** [comment]
@lee-orr This is working very well for us in practice!  We'd like a small addition: To be able to show no properties at all.  Essentially a "none" option
