### ISSUE TITLE
Show longitude and latitude (2 ways)

### ISSUE THREAD

**Issue by brendanjmeade** [brendanjmeade/celeri_ui#23]
1 - Grid lines (that we can toggle on and off): https://github.com/mapbox/mapbox-gl-js/issues/10093

2 - Mouse hover over: https://docs.mapbox.com/mapbox-gl-js/example/mouse-position/

**Comment by jploveless** [comment]
The live coordinates seem to be showing longitude, longitude rather than longitude, latitude

**Comment by lee-orr** [comment]
@jploveless - thanks for pointing this out! fixed.

**Comment by sweply** [comment]
We are trying to run the project, but 
1. unable to load map. Would you help with
2. grid size login needs to understand as well, I need to change the grid size to 3Mx3M. @brendanjmeade @jploveless @lee-orr @Emilycm-97
