### ISSUE TITLE
"Sticky" vertex in Merge operation

### ISSUE THREAD

**Issue by jploveless** [brendanjmeade/celeri_ui#24]
I am trying to merge two adjacent vertices, and it seems that the second selection isn't recognizing the clicked vertex. 

I'm working in the SW United States, selecting one vertex: 
<img width="800" alt="Screen Shot 2022-03-02 at 9 49 16 AM" src="https://user-images.githubusercontent.com/7537266/156385505-cf68a0e2-66fc-4985-acbc-f8a4e2e00354.png">

and trying to merge with its neighbor to the north: 
<img width="800" alt="Screen Shot 2022-03-02 at 9 49 30 AM" src="https://user-images.githubusercontent.com/7537266/156385585-20613197-a676-45b2-af14-dd6cac8d9c45.png">

but when I click the neighboring vertex, the merge is done with a far-away vertex: 
<img width="800" alt="Screen Shot 2022-03-02 at 9 49 35 AM" src="https://user-images.githubusercontent.com/7537266/156385663-799312d0-ccd0-4761-863f-656f5c2ce559.png">

There seems to be something special about this second vertex, as it is the one that is selected regardless of where I try to complete the merge.

**Comment by lee-orr** [comment]
Should be resolved in the latest version
