### ISSUE TITLE
Aesthetics (small)

### ISSUE THREAD

**Issue by brendanjmeade** [brendanjmeade/celeri_ui#27]
@lee-orr As we appear to be getting close to finishing up (yay!) I want to request a few aesthetic changes

1. Can we make the default font size smaller?  Maybe 20?  We do a lot of work on laptop screens, and this would reduce the footprint of the text boxes.
2. Flip foreground text to white and background fill to black (see attached figure)
3. Sharp corners for boxes.  Currently, the boxes that contain text (both large and small) have rounded corners.  Can we make these sharp corners?

![celeri_ui 001](https://user-images.githubusercontent.com/4225359/159804175-6e6d64fd-f7c7-42c1-813e-3b4efb478ff0.png)

**Comment by lee-orr** [comment]
@brendanjmeade - can you take a look at it today and let me know what you think?

**Comment by brendanjmeade** [comment]
@lee-orr This is looking so good!  One small change for the interaction box at the lower right-hand corner (see attached).  The scrollbar covers up the right edge of the filename dropdowns including the small downfacing arrow indicating.  Can we move the scroll bar just to right so that it doesn't cover up anything?

<img width="663" alt="Screen Shot 2022-03-24 at 8 17 17 PM" src="https://user-images.githubusercontent.com/4225359/160030507-0865a2f3-0163-4763-8965-4d0a46f409c6.png">
