### ISSUE TITLE
Specifying filenames when saving files

### ISSUE THREAD

**Issue by brendanjmeade** [brendanjmeade/celeri_ui#29]
@lee-orr celeri_ui is now producing output files that work really well with the python celeri code!  This is fantastic for us.

When saving files, we'd like to be able to specify the file name of the file that will be saved.  We'll do this frequently as we iterate on files.

**Comment by lee-orr** [comment]
@brendanjmeade @jploveless @Emilycm-97 - does the workflow I added work for you, or would you prefer a more traditional "save as" button that pops up a file selector?

**Comment by brendanjmeade** [comment]
@lee-orr Thanks for the followup!  I'd like a more traditional save as button and file selector if that's possible/relatively straightforward.

**Comment by lee-orr** [comment]
Of course - It should definitely be possible.

**Comment by brendanjmeade** [comment]
Fantastic, this would be a straightforward workflow!

**Comment by jploveless** [comment]
Thanks @lee-orr ! I do think that some visual confirmation that the new file has been saved would be good, but maybe that will inherently be part of a more traditional save file dialog.

**Comment by lee-orr** [comment]
This appears in the Segment, Block& Velocities panels separately, as a save as button:
![image](https://user-images.githubusercontent.com/10376144/162766586-f6b3754a-7460-4fe5-a8a7-cfe7b7c7e659.png)

I realize in retrospect I should also add something similar for command files. However, with #32  I'm actually going to be fully adapting the way we access/interact with the file system, so I'll make sure to make it clearer

**Comment by brendanjmeade** [comment]
Sounds good!  "Save As" is working well now.  Getting access to the files directly in our folder structure will be awesome!
