### ISSUE TITLE
Numbers 

### ISSUE THREAD

**Issue by Emilycm-97** [brendanjmeade/celeri_ui#31]
Hi @lee-orr , 

When I try to add an extra cvs file and treat its information as generic segment a bunch of numbers show up along such segments and we do not know to take them off. See screnshoot below. 
<img width="1743" alt="Screen Shot 2022-04-04 at 11 47 14 AM" src="https://user-images.githubusercontent.com/95097324/161585696-4d1108f8-6cad-4187-81f1-a5fd89eacdd8.png">

**Comment by lee-orr** [comment]
@Emilycm-97  Can you send me the CSV? I have a hunch, but I need a copy of it to verify

**Comment by Emilycm-97** [comment]
Of course!
[anatolia_fault_map_arpat_and_saroglu_endpoints_only.csv](https://github.com/brendanjmeade/celeri_ui/files/8411686/anatolia_fault_map_arpat_and_saroglu_endpoints_only.csv)

**Comment by lee-orr** [comment]
Thanks! The issue was the existence of a column without a name. I adjusted the code so that it will ignore any unnamed columns in when plotting data along a segment.

**Comment by Emilycm-97** [comment]
Thank you so much! It's working perfectly now.
