### ISSUE TITLE
Access files from multiple directories? 

### ISSUE THREAD

**Issue by jploveless** [brendanjmeade/celeri_ui#32]
This may not be possible or advisable due to browser-file system interaction, but it would be great to be able to access and save files from multiple directories rather than a single directory. For celeri, we will use a particular directory structure, with all segment files in one directory, all blocks in another, etc. and it would be great to save updated geometry files directly into those directories. However, if this isn't the best approach with the UI, we could write a helper function that moves/copies files from a single UI folder into the corresponding directories.

**Comment by brendanjmeade** [comment]
@jploveless This is a great idea to access the actual file structure that we use!  I've included a schematic of this below.

@lee-orr Could we give celeri_ui access to the entire `data/` folder shown below and then navigate to the files we want?

```
project_name/
├── README.md
├── notebooks/
│   ├── block_model.ipynb
│   ├── visualize_results.ipynb
│   └── resolution_tests.ipynb
├── data/
|   ├── command/
│   |   ├── command_001.json
│   |   └── command_NNN.json
│   ├── segment/
│   │   ├── segment_001.csv
│   │   └── segment_NNN.csv
│   ├── block/
│   │   ├── block_001.csv
│   │   └── block_NNN.csv
│   ├── station/
│   │   ├── station_001.csv
│   │   └── station_NNN.csv
│   ├── mesh/
│   |   ├── mesh_params_001.json
│   |   ├── mesh_params_NNN.json
│   |   ├── mesh_001.msh
│   |   └── mesh_NNN.msh
```

**Comment by lee-orr** [comment]
I'll look into it - it should be possible to get it to work, but will require some experimentation. Can you send me a zipped version of the data folder?

**Comment by brendanjmeade** [comment]
Zip file attached!  Note that this folder unzips to `data_celeri` but the folder in most cases will be called `data`.

[data_celeri.zip](https://github.com/brendanjmeade/celeri_ui/files/8452146/data_celeri.zip)

**Comment by lee-orr** [comment]
This should be working as of today

**Comment by brendanjmeade** [comment]
This. Is. So. Cool.  Very nice!
