### ISSUE TITLE
Segment selection

### ISSUE THREAD

**Issue by Emilycm-97** [brendanjmeade/celeri_ui#37]
Hi, 

I am trying to edit some segments in celeri_ui and the software is not letting select them. I can select some of them but not all of them and I need to be able to modify them. @lee-orr do you have any idea of why is this happening and how to fix it?

**Comment by lee-orr** [comment]
Can you grab a screen recording of your attempt? Or send me a copy of the directory you opened & the specific steps you took? I'm uncertain atm, and it'd be really helpful.

**Comment by Emilycm-97** [comment]
In this screenshot you can see one segment selected in light blue, so that one works. But when I move north and try to select the other I can't do it. Does that makes sense?

<img width="1525" alt="Screen Shot 2022-05-03 at 3 55 49 PM" src="https://user-images.githubusercontent.com/95097324/166558658-aa1e85b6-bb8b-421d-a98e-bbb5ce933394.png">

**Comment by Emilycm-97** [comment]
It returns the coordinates of the segment but I can't selected it, or edit it or anything.

**Comment by lee-orr** [comment]
an you send me the segment file?

**Comment by Emilycm-97** [comment]
[emed0005_block.csv](https://github.com/brendanjmeade/celeri_ui/files/8614069/emed0005_block.csv)

**Comment by Emilycm-97** [comment]
[emed0005_segment.csv](https://github.com/brendanjmeade/celeri_ui/files/8614071/emed0005_segment.csv)

**Comment by lee-orr** [comment]
Thanks! I'm able to reproduce it now, and will work on it first thing in the morning

**Comment by Emilycm-97** [comment]
Thanks!

**Comment by lee-orr** [comment]
Found the issue, the fix will be up in a few minutes.

**Comment by Emilycm-97** [comment]
Great. Please keep us posted.

**Comment by lee-orr** [comment]
It should be up by now
