### ISSUE TITLE
Vertices

### ISSUE THREAD

**Issue by Emilycm-97** [brendanjmeade/celeri_ui#38]
Hi @lee-orr, 

Hope all is well. I'm working with celeri.ui and for some reason it does not let me choose  any vertices  or edit them. Any idea of why? 

Here are the files I'm working with.
[emed0014_segment.csv](https://github.com/brendanjmeade/celeri_ui/files/8662317/emed0014_segment.csv)[emed0014_block.csv](https://github.com/brendanjmeade/celeri_ui/files/8662318/emed0014_block.csv)

**Comment by lee-orr** [comment]
I managed to replicate it, and will look into it today.
In the mean time - there are a couple of work arounds:
- seems like selection with the lasso tool works (it's located in the panel on the left hand side, above the coordinate display) - you click the button, and then click on the map to draw a polygon around the area you want selected, then press enter to select
- alternatively - you can hide the segments from view - at which point the vertices are able to be clicked again

**Comment by lee-orr** [comment]
I found the solution - currently building the fix. It'll be accessible once this is done: https://github.com/brendanjmeade/celeri_ui/actions/runs/2306897596

**Comment by Emilycm-97** [comment]
Alright. Please keep us updated. Thanks!

**Comment by lee-orr** [comment]
Just to be clear - it should be up by now. Normally when I close an issue, it's maybe a few minutes before the new version is online

**Comment by Emilycm-97** [comment]
Got it. I'll try it right away.

**Comment by Emilycm-97** [comment]
Works perfectly. Thank you!
