### ISSUE TITLE
Rename "Velocity/Velocities" to "Station/Stations"

### ISSUE THREAD

**Issue by lee-orr** [brendanjmeade/celeri_ui#43]
@brendanjmeade @jploveless @Emilycm-97 - I originally used the name "Velocity" since I wasn't sure what the actual name for those files was, and was basing it on my memory. However, now that I've had some time with the project and seen the field names in command files, file names & the directory structure, I feel like it's probably worth re-naming to make it consistent with your work flow. Does "Station" fit better with the language you use while working/discussing these?

**Comment by brendanjmeade** [comment]
@lee-orr velocity is fine.  Thanks for checking!
